export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR'
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR'
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
export const GET_SECRET = 'GET_SECRET'
